# Generated by Django 5.0.1 on 2024-01-26 11:44

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', ckeditor.fields.RichTextField(max_length=128, unique=True, verbose_name='Título')),
                ('text', ckeditor.fields.RichTextField(unique=True, verbose_name='Texto')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at: ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at: ')),
            ],
            options={
                'verbose_name': 'Nota',
                'verbose_name_plural': 'Notas',
                'ordering': ['-updated_at'],
            },
        ),
    ]
