# Generated by Django 5.0.1 on 2024-02-14 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="biography",
            field=models.TextField(
                blank=True,
                default="Hello there. I am using Nyra!",
                max_length=256,
                null=True,
            ),
        ),
    ]
